Fix issue with travis using old bundler
We were getting this error:
```
NoMethodError: undefined method `spec' for nil:NilClass
```

Googling lead to: https://github.com/rubygems/rubygems/issues/1419
Which lead to: https://github.com/alphagov/govuk-puppet/pull/6406/files

Looking at our `.travis.yml` files it's now obvious we double defined
`before_install` and the last one was winning, so the line that should
have fixed this issue wasn't running.

It's not clear why this started failing suddenly, but hopefully this
fixes it.